### ISSUE TITLE
Pydantic dependency constraint forces users to use Pydantic V1

### ISSUE THREAD

**Issue by ramon-prieto** [Authress/authress-sdk.py#15]
Authress enforces `pydantic<2` 

The V2 package still provides an API for V1 so this could easily fixed by moving to `>1, <3` and changing imports to

```python
from pydantic.v1 import ...
```

**Comment by wparad** [comment]
Hey @ramon-prieto, it actually was pretty easy to get this upgraded, so I just pushed out a change this morning. All the tests passed and the new version in `3.0.72`. Usually our testing is pretty good, but please let us know if you run into any problems.
