### ISSUE TITLE
Unable to decode JWT

### ISSUE THREAD

**Issue by richiedunk** [Authress/authress-sdk.py#2]
Versions: authress-sdk 1.1.3, PyJWT 2.4.0
Framework: Flask

```python

@app.route("/auth")
def auth_test():
    authorization_token = request.headers.get("authorization")
    authress_client.set_token(authorization_token)
    return {"user": authress_client.get_user_from_token()}

"""
>>>>>>>>>
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
"""
```

I'm happy to fork and raise a PR if this is a bug, just let me know which algo you encode with.

**Comment by richiedunk** [comment]
Tried a few of the examples in the README, same error.

**Comment by wparad** [comment]
Hey, I just saw this, I'm going to throw in the algorithm guess into the check in the library.

**Comment by richiedunk** [comment]
You win the award for quickest fix I've ever seen! Thanks.

**Comment by wparad** [comment]
Whether it fixes the problem remains to be seen ;) . The new version should be `1.1.7`. I wrote this a while ago, it's likely it might be missing some of the newer features of Authress. If you see anything else, feel free to create additional issues, I usually try to keep an eye on our open source repos.

**Comment by richiedunk** [comment]
Hmmm. Now we're getting `jwt.exceptions.InvalidKeyError: Expecting a EllipticCurvePrivateKey/EllipticCurvePublicKey. Wrong key provided for EdDSA algorithms`
