### ISSUE TITLE
Python client not returning Role upon create

### ISSUE THREAD

**Issue by richbrown3232** [Authress/authress-sdk.py#22]
Hi, I use the python client to create a role.  I would like to have back the role_id after it is created.  I use the create_role method to do so and it does the creation.  However, nothing is returned so I'm unable to get the role_id.  I've since switched to pushing my own role_id so I'm not stuck at this point.  The docs say it returns the Role though so it is worth looking into.

Thanks,
Rich

**Comment by wparad** [comment]
This was caused by a slight mismatch in the library's expectations on how to deserialize objects.it is now fixed in the latest version of the library. If you find any more instances of this please let us know.
