### ISSUE TITLE
Updating Access Record failure

### ISSUE THREAD

**Issue by richbrown3232** [Authress/authress-sdk.py#27]
Hi, I'm attempting to update an access record with the following code.

        record = self.authress_client.access_records.update_record(
            record_id=access_record.record_id,
            access_record=authress_access_record,
            expected_last_modified_time=access_record.updated.strftime(
                "%Y-%m-%dT%H:%M:%SZ"
            ),
        )
I have also attempted it without the expected_last_modified_time at all.  For both, I get the following error.

2024-08-15 15:25:51   File "/usr/local/lib/python3.12/site-packages/authress/api/access_records_api.py", line 1662, in update_record_with_http_info
2024-08-15 15:25:51     if _params['if_unmodified_since']:
2024-08-15 15:25:51        ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
2024-08-15 15:25:51 KeyError: 'if_unmodified_since'

Any help would be appreciated.
Thanks,
Rich

**Comment by wparad** [comment]
You've run into an edge case there, we were actually in the process of removing that legacy parameter `if_unmodified_since`, but it looks like it didn't get removed everywhere. I've pushed out a new version that removes references to it. Using `expected_last_modified_time` is the correct parameter and should work (with or without it).

Thanks for finding and reporting this.
